/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    DndItem: typeof import("./src/components/DndItem/DndItem.vue")["default"];
    Shape: typeof import("./src/components/Shape/Shape.vue")["default"];
    VueNode: typeof import("./src/components/VueNode/index.vue")["default"];
  }
}
